const $=s=>document.querySelector(s),H=document.documentElement;
const S=[
["IaaS","Azure Virtual Machines","เช่าเครื่องเสมือน ควบคุมระบบปฏิบัติการเอง","ย้ายระบบเดิมขึ้นคลาวด์","ควบคุมสูง","Infrastructure as a Service ให้ทรัพยากรพื้นฐาน (คำนวณ เครือข่าย ดิสก์)","ผู้ใช้เลือกขนาด VM และระบบปฏิบัติการ ดูแลการติดตั้งและอัปเดตเอง Azure ดูแลฮาร์ดแวร์","Users → Load Balancer → VM → Managed Disk"],
["CaaS","Azure Kubernetes Service (AKS)","บริการ Kubernetes แบบจัดการ","แอปแบบ Microservices","จัดการ Container ได้ง่าย","Container คือแพ็กเกจแอปพร้อมส่วนที่ต้องใช้ Kubernetes คือระบบจัดการ Container จำนวนมาก","AKS จัดการ Control Plane ให้ ผู้ใช้กำหนด Node และ Workload","Registry → AKS Cluster → Pods → Ingress"],
["PaaS","Azure App Service","โฮสต์เว็บแอปและ API โดยไม่ดูแลเซิร์ฟเวอร์","เว็บแอปและ REST API","ลดภาระ Infrastructure","Platform as a Service ให้แพลตฟอร์มพร้อมรันโค้ด","นักพัฒนา Deploy โค้ด Azure ดูแล OS, Patch และการขยายระบบ","Developer → App Service → Database"],
["FaaS","Azure Functions","รันโค้ดเมื่อมี Event โดยไม่จัดการเซิร์ฟเวอร์","ประมวลผลไฟล์หรือข้อความเมื่อมีเหตุการณ์","จ่ายตามการทำงานจริง","Serverless แบบ Function ทำงานเมื่อมี Trigger เช่น HTTP, Timer, Queue","Event ทำให้ Function ทำงานและขยายตามปริมาณ Event (Event-driven)","Event → Function → Storage / Database"],
["DaaS","Azure SQL Database","ฐานข้อมูล SQL แบบจัดการ","ฐานข้อมูลของแอปพลิเคชัน","Backup และ Scaling จัดการให้","Database as a Service ที่ Azure ดูแลการติดตั้งและบำรุงรักษา","Azure จัดการ Backup, ความพร้อมใช้งาน และ Security ส่วนผู้ใช้ออกแบบข้อมูล","App → Azure SQL Database → Backup"],
["Security & Identity","Microsoft Entra ID","บริการ Identity และการเข้าถึง","Single Sign-on และ MFA","ควบคุมสิทธิ์รวมศูนย์","จัดการ Identity, Authentication, Authorization, MFA และ Access Control","ผู้ใช้ยืนยันตัวตนกับ Entra ID แล้วได้สิทธิ์ตามนโยบาย ใช้ร่วมกับ Microsoft Defender for Cloud ตรวจสอบความปลอดภัย","User → Entra ID → Policy → Application"],
["IoT","Azure IoT Hub","เชื่อมต่อและจัดการอุปกรณ์ IoT","เซนเซอร์ในโรงงาน","รับข้อมูลอุปกรณ์จำนวนมาก","Device → Internet → Azure → Data → Analytics/AI","อุปกรณ์ส่งข้อมูลเข้า IoT Hub แล้วส่งต่อไปวิเคราะห์ Azure IoT Operations เป็นบริการสำหรับ Edge (ควรตรวจสถานะล่าสุดบน Microsoft Learn)","Device → IoT Hub → Analytics/AI"],
["STaaS","Azure Blob Storage","Object Storage สำหรับข้อมูลไม่มีโครงสร้าง","เก็บรูป วิดีโอ และ Backup","ขยายได้มาก","Object Storage เก็บไฟล์และข้อมูลจำนวนมากเป็น Object","แอปเข้าถึงข้อมูลผ่าน API/HTTPS","App → Storage Account → Blob Container"],
["Big Data & Analytics","Microsoft Fabric / Azure Synapse Analytics","วิเคราะห์ข้อมูลขนาดใหญ่","Dashboard ธุรกิจ","ตัดสินใจจากข้อมูล","Data → Processing → Analytics → Visualization → Business Decision","Fabric เป็นแพลตฟอร์มข้อมูลแบบรวม ส่วน Synapse เป็นบริการเดิม ควรตรวจหมวดและแนวทางปัจจุบันบน Microsoft Learn","Data Source → Fabric → Power BI"],
["BCaaS","Azure Blockchain Service (ยุติแล้ว)","ไม่มีบริการแบบ Standalone ในปัจจุบัน","ไม่มี","ไม่ระบุ","Azure does not currently provide the former Azure Blockchain Service as an active standalone offering. บริการเดิมถูกยุติ (ผู้จัดทำทราบว่าเลิกในปี 2021 ควรยืนยันกับเอกสาร Microsoft)","ไม่ระบุสถาปัตยกรรม เพื่อไม่อ้างบริการที่ไม่มีอยู่","ไม่มี"],
["LBaaS","Azure Load Balancer","กระจายทราฟฟิกไปหลายเซิร์ฟเวอร์","เว็บที่มีผู้ใช้จำนวนมาก","High Availability","Load Balancing กระจายคำขอเพื่อ Availability และ Scalability","Internet → Load Balancer → Server 1 / 2 / 3","Internet → Load Balancer → Server 1, 2, 3"]];
$("#cards").innerHTML=S.map((s,i)=>`<button class="card" data-i="${i}"><span class="cat">${s[0]}</span><p class="prod">${s[1]}</p><p>${s[2]}</p><p class="k">Use case: ${s[3]}<br>Key benefit: ${s[4]}</p></button>`).join("");
const modal=$("#modal");let last;
$("#cards").onclick=e=>{const b=e.target.closest("[data-i]");if(!b)return;last=b;const s=S[b.dataset.i];
$("#mc").innerHTML=`<h3>${s[0]}: ${s[1]}</h3><h4>What is it?</h4><p>${s[5]}</p><h4>How it works</h4><p>${s[6]}</p><h4>Use case</h4><p>${s[3]}</p><h4>Key benefit</h4><p>${s[4]}</p><h4>Example architecture</h4><p>${s[7]}</p>`;modal.hidden=false;$("#x").focus()};
const close=()=>{modal.hidden=true;last&&last.focus()};$("#x").onclick=close;modal.onclick=e=>e.target===modal&&close();
addEventListener("keydown",e=>e.key==="Escape"&&!modal.hidden&&close());
function tabs(id,box,data,fn){const t=$(id);t.innerHTML=Object.keys(data).map((k,i)=>`<button role="tab" aria-selected="${!i}">${k}</button>`).join("");
const show=k=>{[...t.children].forEach(b=>b.setAttribute("aria-selected",b.textContent===k));$(box).innerHTML=fn(k,data[k])};
t.onclick=e=>e.target.matches("button")&&show(e.target.textContent);show(Object.keys(data)[0])}
const C={IaaS:["สูง (ผู้ใช้ดูแล OS)","ผู้ใช้ดูแล OS และแอป","ปรับขนาด VM หรือจำนวน VM","ย้ายระบบเดิม","ผู้ดูแลระบบ"],CaaS:["ปานกลาง","ผู้ใช้ดูแล Workload Azure ดูแล Control Plane","ปรับจำนวน Pod/Node","Microservices","DevOps"],PaaS:["ปานกลางถึงต่ำ","Azure ดูแลแพลตฟอร์ม","ปรับตามแผนบริการ","เว็บแอป/API","นักพัฒนา"],FaaS:["ต่ำ","Azure ดูแลเกือบทั้งหมด","ขยายตาม Event","งานแบบ Event-driven","นักพัฒนา"],DaaS:["ปานกลางถึงต่ำ","Azure ดูแล Backup/Patch","ปรับขนาดตามระดับบริการ","ฐานข้อมูลแอป","นักพัฒนา/DBA"],STaaS:["ต่ำ","Azure ดูแลระบบจัดเก็บ","ขยายได้มาก","ไฟล์/Backup","ทุกกลุ่ม"]};
const L=["Control","Management","Scalability","Use Case","Target User"];
tabs("#tabs","#cmp",C,(k,v)=>`<h3>${k}</h3>`+L.map((l,i)=>`<p><b>${l}:</b> ${v[i]}</p>`).join("")+`<p class="k">เนื้อหาเชิงเปรียบเทียบแบบสรุปสำหรับการศึกษา</p>`);
const P={"Pay-as-you-go":"จ่ายตามการใช้งานจริง ไม่มีข้อผูกมัดระยะยาว","Reservations":"จอง Resource ล่วงหน้าเพื่อรับส่วนลดตามเงื่อนไข","Savings Plans":"ผูกพันค่าใช้จ่ายต่อชั่วโมงเพื่อรับส่วนลดตามเงื่อนไข","Free Account":"Microsoft มี Free Account และบริการฟรีบางรายการ เงื่อนไขเปลี่ยนได้ ตรวจสอบที่ azure.microsoft.com/free","Cost Management":"ใช้ Microsoft Cost Management ดู วิเคราะห์ และตั้งงบประมาณค่าใช้จ่าย"};
tabs("#ptabs","#pbox",P,(k,v)=>`<h3>${k}</h3><p>${v}</p>`);
const R=[["Southeast Asia","สิงคโปร์",103.8,1.35,"Region ใกล้ไทยที่สุดแห่งหนึ่ง"],["East Asia","ฮ่องกง",114.2,22.3,"Region ในเอเชียตะวันออก"],["Japan East","ญี่ปุ่น",139.7,35.7,"Region ในญี่ปุ่น"],["Indonesia Central","อินโดนีเซีย",106.8,-6.2,"เปิดเมื่อ พ.ค. 2025 มี 3 Availability Zone (Microsoft)"],["Malaysia West","มาเลเซีย",101.7,3.1,"เปิดเมื่อ พ.ค. 2025 มี 3 Availability Zone (Microsoft)"],["Central India","อินเดีย",73.9,18.5,"Region ในอินเดีย"],["Australia East","ออสเตรเลีย",151.2,-33.9,"Region ในออสเตรเลีย"],["West Europe","เนเธอร์แลนด์",4.9,52.4,"Region ในยุโรป"],["East US","สหรัฐฯ",-78.4,37.4,"Region ในอเมริกาเหนือ"],["Brazil South","บราซิล",-46.6,-23.5,"Region ในอเมริกาใต้"],["South Africa North","แอฟริกาใต้",28.2,-26.2,"Region ในแอฟริกา"],["Thailand (planned)","ไทย",100.5,13.75,"ประกาศแผนสร้าง ยังไม่เปิดให้บริการ ณ ปี 2026"]];
$("#world").innerHTML='<rect width="360" height="180" fill="none"/>'+Array.from({length:17},(_,i)=>`<line x1="${i*22.5}" y1="0" x2="${i*22.5}" y2="180" stroke="currentColor" opacity=".08"/>`).join("")+R.map((r,i)=>{const x=r[2]+180,y=90-r[3];return`<circle class="dot${i==11?" plan":""}" cx="${x}" cy="${y}" r="2.2"/><circle class="pinh" tabindex="0" role="button" aria-label="${r[0]}" data-i="${i}" cx="${x}" cy="${y}" r="7"/>`}).join("");
const pin=e=>{const c=e.target.closest("[data-i]");if(!c||!c.classList.contains("pinh"))return;const r=R[c.dataset.i];$("#pin").innerHTML=`<h3>${r[0]}</h3><p>${r[1]}</p><p>${r[4]}</p>`};
$("#world").onclick=pin;$("#world").onkeydown=e=>(e.key==="Enter"||e.key===" ")&&(e.preventDefault(),pin(e));
const CE=[["Azure Fundamentals","AZ-900","Fundamentals","พื้นฐานคลาวด์และ Azure"],["Azure AI Fundamentals","AI-900","Fundamentals","พื้นฐาน AI"],["Azure Data Fundamentals","DP-900","Fundamentals","พื้นฐานข้อมูล"],["Security, Compliance, and Identity Fundamentals","SC-900","Fundamentals","พื้นฐานความปลอดภัย"],["Azure Administrator","AZ-104","Associate","ผู้ดูแลระบบ Azure"],["Azure Developer","AZ-204","Associate","นักพัฒนา Azure"],["Azure Solutions Architect Expert","AZ-305","Expert","ออกแบบโซลูชัน"],["DevOps Engineer Expert","AZ-400","Expert","DevOps"]];
$("#certs").innerHTML=CE.map((c,i)=>`<li><button aria-pressed="false" data-i="${i}">${c[1]} · ${c[2]}</button></li>`).join("");
$("#certs").onclick=e=>{const b=e.target.closest("button");if(!b)return;document.querySelectorAll("#certs button").forEach(x=>x.setAttribute("aria-pressed",x===b));const c=CE[b.dataset.i];$("#cbox").innerHTML=`<h3>${c[0]}</h3><p>Exam code: ${c[1]} · Level: ${c[2]}</p><p>Target skill: ${c[3]}</p><p class="k">ตรวจสอบสถานะข้อสอบล่าสุดที่ Microsoft Learn</p>`};
const A=[["User","ผู้ใช้เข้าถึงเว็บผ่านอินเทอร์เน็ต"],["Azure Front Door","จุดเข้าถึงระดับโลกสำหรับเว็บแอป กระจายทราฟฟิก"],["Azure App Service","รันแอปพลิเคชัน"],["Azure SQL Database","ฐานข้อมูลของแอป"],["Azure Blob Storage","เก็บไฟล์และสื่อ"],["Microsoft Fabric","วิเคราะห์ข้อมูล"]];
$("#arch-flow").innerHTML=A.map((a,i)=>`<button data-i="${i}">${a[0]}</button>`).join('<span aria-hidden="true">→</span>');
$("#arch-flow").onclick=e=>{const b=e.target.closest("button");b&&($("#abox").innerHTML=`<h3>${A[b.dataset.i][0]}</h3><p>${A[b.dataset.i][1]}</p>`)};
const go=h=>$(h).scrollIntoView({behavior:"smooth"}),menu=$("#menu"),bg=$("#burger");
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
menu.onclick=e=>{if(e.target.matches("a")){menu.classList.remove("open");bg.setAttribute("aria-expanded",false)}};
bg.onclick=()=>bg.setAttribute("aria-expanded",menu.classList.toggle("open"));
const th=$("#theme"),set=t=>{H.dataset.theme=t;th.textContent=t=="dark"?"Light":"Dark";try{localStorage.setItem("theme",t)}catch(e){}};
try{set(localStorage.getItem("theme")||"dark")}catch(e){}
th.onclick=()=>set(H.dataset.theme=="dark"?"light":"dark");
$("#top").onclick=()=>scrollTo({top:0,behavior:"smooth"});
const links=[...menu.children];
addEventListener("scroll",()=>{const y=scrollY,m=H.scrollHeight-innerHeight;$("#bar").style.width=(m>0?y/m*100:0)+"%";$("#top").hidden=y<500;
let cur=links[0];links.forEach(a=>{const s=$(a.getAttribute("href"));s&&s.getBoundingClientRect().top<120&&(cur=a)});links.forEach(a=>a.classList.toggle("on",a===cur))},{passive:true});
